
project_id = "felhkxffcgtyfnorddas"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry_limit = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhooks]
verify_jwt = false

[functions.send-team-invitation]
verify_jwt = true
