// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwjqajsncpkvdtyixuzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3anFhanNuY3BrdmR0eWl4dXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODM0ODMsImV4cCI6MjA2NzA1OTQ4M30.XBuIrK78Z9sMI_mAItq5fgMGaMGpn0FcZqluWq2KvzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});