// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://felhkxffcgtyfnorddas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlbGhreGZmY2d0eWZub3JkZGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzUxMDMsImV4cCI6MjA2NzU1MTEwM30.ZgHPTt0V60FJ2c0f8sqhD6DriwJH5ljhEKRQuoqmEpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});